[package]
name = "pombase-gocam-process"
version = "0.24.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
pombase-gocam = { git = "https://github.com/pombase/pombase-gocam.git", version = "0.14.0" }
serde_derive = "1.0"
serde_json = "1.0"
serde = "1.0"
petgraph = "0.7"
bon = "3"
anyhow = "1.0"
